using System;
using System.Windows.Forms;
using ElearningWinForms.Data;

namespace ElearningWinForms
{

    public partial class AssignmentForm : Form
    {
        public AssignmentForm()
        {
            InitializeComponent();
        }

        public int CurrentTeacherId { get; set; }

        // Add this method to your AssignmentForm class if it does not exist.
        // This is a minimal stub to resolve CS0103. In a real WinForms project,
        // this method is auto-generated in the designer file. If you are missing
        // the designer file, you should use the WinForms designer to add controls.

        private void InitializeComponent()
        {
            // This method should be auto-generated by the WinForms designer.
            // If you are hand-writing forms, you can leave this empty or add control initialization here.
        }

        private void AssignmentForm_Load(object sender, EventArgs e)
        {
            // TODO: load danh sách bài tập theo Section mà GV đang chọn
        }

        private void btnCreateAssignment_Click(object sender, EventArgs e)
        {
            // TODO: dùng DbHelper.ExecuteNonQuery để INSERT vào Assignments.
        }

        private void btnUpdateAssignment_Click(object sender, EventArgs e)
        {
            // TODO: UPDATE Assignments.
        }

        private void btnDeleteAssignment_Click(object sender, EventArgs e)
        {
            // TODO: DELETE Assignments.
        }
    }
}
