using System;
using System.Data;
using System.Windows.Forms;
using ElearningWinForms.Data;

namespace ElearningWinForms
{
    public partial class CourseForm : Form
    {
        public CourseForm()
        {
            InitializeComponent();
        }


        public int CurrentUserId { get; set; }
        public string CurrentRole { get; set; }  // "SV", "GV", "Admin"

        // Add this method to your CourseForm class if it does not exist.
        // This is a minimal stub to resolve CS0103. In a real WinForms project,
        // this method is auto-generated in the designer file. If you are missing
        // the designer file, you should use the WinForms designer to add controls.

        private void InitializeComponent()
        {
            // This method is usually auto-generated by the WinForms designer.
            // If you are hand-writing forms, you can initialize controls here.
        }

        private void CourseForm_Load(object sender, EventArgs e)
        {
            // Ví dụ load danh sách khóa học – tạm thời chỉ để TODO
            // DataTable courses = DbHelper.GetDataTable("SELECT * FROM Courses");
            // TODO: gán vào DataGridView sau khi bạn tạo control.
        }

        // Ví dụ nút Đăng ký khóa học cho SV
        private void btnEnroll_Click(object sender, EventArgs e)
        {
            // TODO: sau này dùng DbHelper.ExecuteNonQuery để INSERT vào Enrollments.
        }
    }
}
